### ISSUE TITLE
Error trying to install

### ISSUE THREAD

**Issue by spoonie72** [satrik/homebridge-bslamp2#10]
Trying to install in homebridge and I get the following:

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-10/bluetooth_hci_socket-0.5.3-10-node-v115-linux-arm.tar.gz

**Comment by satrik** [comment]
does the installation abort at this point, or does it just go on after the error?

it's by the way a dependency of a dependency of a dependency^^ so unfortunately I have no influence on it at all

**Comment by satrik** [comment]
no answer, so I close this issue
