### ISSUE TITLE
Cannot change only the brightness via HK automation.

### ISSUE THREAD

**Issue by GoanSausage** [satrik/homebridge-bslamp2#3]
HK Automations can only turn the lamp ON without changing the colour. 

The moment one configures brightness level, the lamps ALSO change colour.

In my case, Any such automation takes the Lamp out of the much brighter (White+Colour Temp) mode into the much dimmer RGB mode. I can post a  video if necessary. Tested with multiple lamps.

Changing the brightness manually in the App or via Siri changes brightness WITHOUT affecting colour.

Plugin is rock solid otherwise.

**Comment by satrik** [comment]
This isn't related to the plugin, this is simply not possible with the default Home App's automations.
You should try an alternative App like _Controller for HomeKit_ or _Eve_ as they allow a lot more settings for automations, also setting separated brightness/hue/power :)

**Comment by GoanSausage** [comment]
> This isn't related to the plugin, this is simply not possible with the default Home App's automations.
> You should try an alternative App like _Controller for HomeKit_ or _Eve_ as they allow a lot more settings for automations, also setting separated brightness/hue/power :)

No, it definitely is. HK is able to just control brightness without affecting hue, via the HK app AND via Siri AND via HK automations. 

I had the exact same automations running with these same lamps connected directly to HK. Recreating the automations with the lamps connected via this homeBridge plugin makes it impossible to control brightness without also setting the hue.
