### ISSUE TITLE
Any Lamp offline makes usage spike to 100%

### ISSUE THREAD

**Issue by GoanSausage** [satrik/homebridge-bslamp2#4]
One of my 4 BS-II lamps does not have a power backup and when it loses power and goes offline, CPU usage on my Pi spikes to 100%, slowing down PiHole and making HomeBridge unresponsive until power is restored to that lamp.

Disabling this plugin fixes the issue.

**Comment by satrik** [comment]
Hey sorry for the late response.
Just tested it right now and I can't reproduce it. If I unplug any of my lamps, Homebridge just shows the expected error message(s) in the log and the CPU usage doesn't increase - the plugin don't even has any logic to repeat tasks if something isn't reachable, it only logs the error and don't do anything else.

have you running any automation or anything else which aggressively tries to get the state of the lamps?
